### ISSUE TITLE
Source for GANverse3D 

### ISSUE THREAD

**Issue by WyattAutomation** [nv-tlabs/GANverse3D#1]
Is this a placeholder for an eventual release of GANverse3D?  Per the Nvidia blogs it looks like there are still some conferences where this is being demoed this month--that makes me hopeful it'll be shared here in the near future (makes sense to hold off on that at least until demos are done etc).

Thanks for your work on this--excited to take it for a test drive!

Edit: found the link to the site with "source: coming soon",-- closing.

**Comment by WyattAutomation** [comment]
Saw the link in the deployment to the page with the "coming soon" for the code--good stuff!  My apologies for not checking that sooner.  (closing this out; please don't feel obligated to reply to this).  Very excited for the upcoming release of this model--I can't express how useful open tools like this are to people who want to leverage AI for developing and enhancing art, so thank you for not just advancing the field but keeping these tools open and accessible!
 
Been watching this repo closely, as I plan on experimenting with it  mod NPC sprite assets in The Elder Scrolls II: DaggerFall (Daggerfall Unity, specifically), to bring them into fully rigged 3D models using a combination of models, techniques, and intermediate steps.  

I have a rough processing pipeline tested using pixel2style2pixel to go from sprites to photorealistic images for the portraits, and then to another art style using StyleGAN2-ADA, and I'm working on retraining both to do the same for fully-body sprite images with a custom blend of art styles for the second step.  For the next step into 3D models, I am thinking about using StyleGAN2 to render textures from the image outputs of the applied art style, then using the photorealistic images to generate 3D models via GANverse3D.  The final steps will be to rig the generated model using key-point detection (skeletal detection from 2D), try to apply enhancements to the 3D model by leveraging/aligning detected keypoints from the image to the model (normalization between the two--remove distortion, improve detail), then UV remap the textures prior to rasterization.  I may have butchered a lot of terminology there but GANverse3D potentially fits several useful roles in the upcoming steps into bringing retro game sprites into full 3D.

There are 9 sprites in the attached mosaic here, 3 thumbnails each.  Left thumbnails are super resolution enhancements of original sprite portrait images from Daggerfall, middle is pixel2style2pixel conversion to photorealistic renders of the sprites, right uses StyleGAN2-ADA to transfer from the middle photorealism image to a Renaissance art style (easily interchangeable with other styles):  
![example3](https://user-images.githubusercontent.com/12909139/123679235-4779a780-d815-11eb-8276-da92becfe4ae.jpg)

The "photo to art" process from the middle photo to the one on the right for each sprite loses too much is lost in translation, likely due to the nature of the dataset it was trained on (limited diversity in Renaissance art etc) so that will be replaced.

Anyway, sorry for writing a book here, just really wanted to share why I'm so excited to try this out.  I'll post a follow up after it's released and hopefully have some really cool results!

**Comment by DaddyWesker** [comment]
One year later there are still no code available.

**Comment by WyattAutomation** [comment]
> One year later there are still no code available.

It's probably available as a plugin (compiled binary) on 'Omniverse' for the low price of $40,000 a year (non-commercial license only).
